# Generated by Django 4.0.5 on 2022-06-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_category_alter_article_options_article_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
